name: CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test:
    name: "Test with Java ${{ matrix.java }}"
    strategy:
      matrix:
        java: [ 8, 11, 17 ]
    runs-on: ubuntu-latest
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v3
      - name: "Setup Java ${{ matrix.java }}"
        uses: actions/setup-java@v3
        with:
          java-version: "${{ matrix.java }}"
          distribution: "adopt"
      - name: "Test with Gradle"
        run: "chmod +x ./gradlew && ./gradlew check"
  
  artifact:
    name: "Publish Artifact"
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v3
      - name: "Setup Java 17"
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"
      - name: "Build with Gradle"
        run: "chmod +x ./gradlew && ./gradlew fatJar"
      - name: "Upload Artifact"
        uses: actions/upload-artifact@v3
        with:
          name: Artifact
          path: coconut/build/libs
          retention-days: 90