name: "Code coverage"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  coverage:
    name: "Code coverage"
    runs-on: ubuntu-latest
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v3
      - name: "Setup Java 17"
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"
      - name: "Test with Gradle"
        run: "chmod +x ./gradlew && ./gradlew check"
      - name: "Code Coverage Summary"
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: "coconut/src/main/java/com/compvisia/coconut/Event/Event.java"
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '60 80'
      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md
