on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  coverage:
    name: "Code coverage"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
      - name: "Setup Java 17"
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"
      - name: "Code Coverage Summary"
        uses: irongut/CodeCoverageSummary@v1.3.0-beta
        with:
          filename: "coconut/src/main/java/com/compvisia/coconut/Event/Event.java"
